#!/usr/bin/env python

import os
import sys
from diffusers import StableDiffusionPipeline


model_id = "runwayml/stable-diffusion-v1-5"
MODEL_CACHE = "diffusers-cache"
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    cache_dir=MODEL_CACHE,
    use_auth_token=sys.argv[1],
)
